const ROLE_TO_ELEMENT_TAG_NAME_MAP = {
  alert: 'div',
  alertdialog: 'dialog',
  application: 'div',
  article: 'article',
  banner: 'header',
  button: 'button',
  cell: 'td',
  checkbox: 'input',
  columnheader: 'th',
  combobox: 'div',
  complementary: 'aside',
  contentinfo: 'footer',
  definition: 'dfn',
  dialog: 'dialog',
  directory: 'ul',
  document: 'div',
  feed: 'div',
  figure: 'figure',
  form: 'form',
  grid: 'table',
  group: 'div',
  heading: 'h1',
  img: 'img',
  link: 'a',
  list: 'ul',
  listitem: 'li',
  log: 'div',
  main: 'main',
  marquee: 'marquee',
  math: 'math',
  menu: 'ul',
  menubar: 'nav',
  menuitem: 'li',
  meter: 'meter',
  navigation: 'nav',
  none: 'div',
  note: 'aside',
  option: 'option',
  paragraph: 'p',
  presentation: 'div',
  progressbar: 'progress',
  radio: 'input',
  radiogroup: 'fieldset',
  region: 'section',
  row: 'tr',
  rowgroup: 'tbody',
  rowheader: 'th',
  scrollbar: 'div',
  searchbox: 'input',
  separator: 'hr',
  slider: 'input',
  spinbutton: 'input',
  status: 'div',
  summary: 'summary',
  switch: 'input',
  tab: 'button',
  table: 'table',
  tablist: 'ul',
  tabpanel: 'section',
  term: 'dt',
  timer: 'time',
  toolbar: 'div',
  tooltip: 'div',
  tree: 'ul',
  treegrid: 'table',
  treeitem: 'li',
} as const;

const ARIA_LEVEL_TO_ELEMENT_TAG_NAME_MAP = {
  1: 'h1',
  2: 'h2',
  3: 'h3',
  4: 'h4',
  5: 'h5',
  6: 'h6',
};

const ROLE_TO_INPUT_TYPE_MAP = {
  checkbox: 'checkbox',
  radio: 'radio',
  searchbox: 'search',
  slider: 'range',
  spinbutton: 'number',
  switch: 'checkbox',
};

export { ARIA_LEVEL_TO_ELEMENT_TAG_NAME_MAP, ROLE_TO_ELEMENT_TAG_NAME_MAP, ROLE_TO_INPUT_TYPE_MAP };
